In [16]:
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv(r'C:\Users\shrikant\Desktop\content\SEM2\Machine Learning\LAB\Dataset\Blood Transfusion Service Center.csv')

In [4]:
X = data.iloc[0:150,0:2]
y = data.iloc[0:150,4]

In [5]:
X

     Recency (months)  Frequency (times)
0                   2                 50
1                   0                 13
2                   1                 16
3                   2                 20
4                   1                 24
5                   4                  4
6                   2                  7
7                   1                 12
8                   2                  9
9                   5                 46
10                  4                 23
11                  0                  3
12                  2                 10
13                  1                 13
14                  2                  6
15                  2                  5
16                  2                 14
17                  2                 15
18                  2                  6
19                  2                  3
20                  2                  3
21                  4                 11
22                  2                  6
23                  2                  6
24                  9                  9
25                  4                 14
26                  4                  6
27                  4                 12
28                  4                  5
29                  4                  8
..                ...                ...
120                 2                  3
121                 4                  5
122                 2                  6
123                 2                  5
124                 2                  4
125                 2                  5
126                 4                  8
127                 2                  4
128                 4                  8
129                 2                  2
130                 4                  5
131                 2                 12
132                 2                  2
133                 4                  6
134                 2                 11
135                 2                  3
136                 2                  5
137                 2                 12
138                 9                  5
139                 2                  2
140                 2                  9
141                 5                 14
142                 4                  3
143                 4                  3
144                 4                  2
145                 4                  3
146                 6                  3
147                 2                  2
148                 2                  2
149                 2                  2

[150 rows x 2 columns]

In [6]:
y

0      1
1      1
2      1
3      1
4      0
5      0
6      1
7      0
8      1
9      1
10     0
11     0
12     1
13     0
14     1
15     1
16     1
17     1
18     1
19     1
20     1
21     0
22     1
23     1
24     0
25     0
26     0
27     1
28     1
29     0
      ..
120    1
121    1
122    1
123    1
124    0
125    0
126    1
127    0
128    1
129    1
130    0
131    0
132    0
133    0
134    0
135    0
136    0
137    0
138    0
139    0
140    0
141    0
142    0
143    0
144    1
145    1
146    0
147    0
148    1
149    0
Name: donated, Length: 150, dtype: int64

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [8]:
# Train the scaler, which standarizes all the features to have mean=0 and unit variance
sc = StandardScaler()
sc.fit(X_train)

C:\Users\shrikant\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [9]:
# Apply the scaler to the X training data
X_train_std = sc.transform(X_train)

# Apply the SAME scaler to the X test data
X_test_std = sc.transform(X_test)

C:\Users\shrikant\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.

C:\Users\shrikant\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  """

In [10]:
ppn = Perceptron(n_iter=40, eta0=0.1, random_state=0)
ppn.fit(X_train_std, y_train)

C:\Users\shrikant\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:152: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)

Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=0.1,
      fit_intercept=True, max_iter=None, n_iter=40, n_iter_no_change=5,
      n_jobs=None, penalty=None, random_state=0, shuffle=True, tol=None,
      validation_fraction=0.1, verbose=0, warm_start=False)

In [11]:
y_pred = ppn.predict(X_test_std)

In [12]:
y_pred

array([0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0], dtype=int64)

In [13]:
y_test

123    1
41     0
33     1
95     0
24     0
86     0
15     1
72     1
68     0
45     1
60     0
57     1
136    0
48     0
44     1
107    0
42     1
83     0
26     0
7      0
47     0
67     0
71     0
70     0
16     1
90     1
84     1
129    1
59     0
3      1
79     0
114    0
30     0
10     0
52     0
28     1
58     0
8      1
88     0
99     1
0      1
103    0
144    1
133    0
97     1
Name: donated, dtype: int64

In [14]:
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

Accuracy: 0.62